---
title: "Data Imputation and Cleaning of Property Values"
output: html_notebook
---

```{r}
#0. read in data and library -----------------------------------------------------------
path <- "~/PetGit/ImputationClusterAnalysis/"
setwd(path)
library(data.table)
library(reshape2)
library(stringr)
library(Amelia)
library(Rcpp) 
library(DMwR2) # pkg impute missing values from median/mode of k nearest neighbors
library(ggplot2)
library(Rcpp)
library(plyr)
```

```{r}
data.url<-"https://raw.githubusercontent.com/EGjohnson/ImputationClusterAnalysis/7959de2efcf1e264daf8dad2b604e6718d411409/Sales_new.txt"
#prop.sale <- fread(data.url,na.strings = c(""," ",NA,"NA"))
prop.sale<-fread("Sales_new.txt" ,na.strings = c(""," ",NA,"NA"))
```
### 1. Examine Data
```{r}
head(prop.sale)
```


### 2. write summary function for easy display
```{r}
line<-function(x){paste(replicate(x, "="), collapse = "")}

sum.funct<-function(i,j,n){
  print(summary(data.frame(prop.sale[,i:j])))
  print(line(n))}
```

### 3. Convert datatypes,drop unwanted data and rename columns.
```{r}
prop.sale <- subset(prop.sale, select = -c(SALE_PK,AUT_SNAPSHOT_DATE,VCS,DIST,SALE_PRICE_SOURCE,SEQ) )

```

```{r}
factor.this<-c("SALE_TYPE","STORY_HEIGHT")
prop.sale[,c(3,6)]<-lapply(prop.sale[,c(3,6)], as.factor) #categorical variables to factor
prop.sale[,c(4,5,7)]<-lapply(prop.sale[,c(4,5,7)], as.numeric) #categorical variables to factor
prop.sale[,8]<-as.Date(prop.sale$SALE_DATE)
prop.sale$sale.years<-as.numeric((prop.sale$SALE_DATE-min(prop.sale$SALE_DATE)))/365
```

```{r}
sum.funct(1,4,150)
sum.funct(5,9,150)
```
```{r}
my.bins<-60
min.val<-100000
max.val<-300000
my.col<-c("PRICE","darkgreen")

prop.sale.sub<-subset(prop.sale,PRICE>min.val & PRICE<max.val)
ggplot(data=prop.sale.sub,aes_string(my.col[1])) + 
geom_histogram(bins=my.bins,fill=my.col[2])+xlim(c(min.val,max.val))
```

```{r}
saveRDS(prop.sale,"propsale.rds")
```

We can see in the below tabplot that (as is to be expected) we have missing values in YEAR_BUILT, STORY_HEIGHT AND BLDGE_SIZE for the LAND ONLY category in SALE_TYPE.
```{r Fig2, echo=TRUE, fig.height=5, fig.width=10}
#readRDS("propsale.rds)
library(tabplot)
tableplot(prop.sale,select=c(PRICE,SALE_TYPE,YEAR_BUILT,STORY_HEIGHT,BLDG_SIZE,SALE_DATE),sortCol=SALE_TYPE)
```
```{r Fig1, echo=TRUE, fig.height=8, fig.width=10}
tab.prop.dat<-subset(prop.sale,SALE_TYPE!="LAND ONLY")
tableplot(tab.prop.dat,select=c(PRICE,SALE_TYPE,YEAR_BUILT,STORY_HEIGHT,BLDG_SIZE,SALE_DATE),sortCol=BLDG_SIZE,from=0,to=100)
```

